name: Rust
on:
  push:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: sudo apt install protobuf-compiler libzmq5-dev

      # - uses: dtolnay/rust-toolchain@master
      #   with:
      #     toolchain: stable
      #     components: rustfmt
      #
      # - name: Set up cargo cache
      #   uses: actions/cache@v3
      #   continue-on-error: false
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      #     restore-keys: ${{ runner.os }}-cargo-
      # - name: Lint
      #   run: |
      #     cargo fmt --all -- --check
      #     cargo clippy -- -D warnings
